# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pryaniky.com' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON', '~> 4.0'

  target 'Pryaniky.comTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Pryaniky.comUITests' do
    # Pods for testing
  end

end
